# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: SFIAplus framework
email: mberthelemy@wyversolutions.co.uk
description: > # this means to ignore newlines until "baseurl:"
  Copyright &copy; BCS
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://bcs.uk" # the base hostname & protocol for your site
twitter_username: SFIAplus
github_username:  berthelemy

# Build settings
markdown: kramdown

post_dirs: false

category-list: ['Strategy and architecture', 'Change and transformation', 'Development and implementation', 'Delivery and operation', 'Skills and quality','Relationships and engagement']
