# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Induction Portal
email: Your support address
description: > # this means to ignore newlines until "baseurl:"
  Copyright &copy; Your company
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://your-url.co.uk" # the base hostname & protocol for your site
twitter_username: berthelemy
github_username:  berthelemy

# Build settings
markdown: kramdown

post_dirs: false

category-list: ['Strategy and architecture', 'Change and transformation', 'Development and implementation', 'Delivery and operation', 'Skills and quality','Relationships and engagement']

collections:
 systems_info:
    output: true
